name: Deploy Frontend to AliOSS
on:
  push:
    branches: [ main ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies & Build
        run: |
          npm install
          npm run build

      - name: Install ossutil
        run: |
          wget https://gosspublic.alicdn.com/ossutil/1.7.16/ossutil64
          chmod +x ossutil64
          sudo mv ossutil64 /usr/local/bin/ossutil

      - name: Upload dist to AliOSS
        env:
          OSS_ACCESS_KEY_ID: ${{ secrets.OSS_ACCESS_KEY_ID }}
          OSS_ACCESS_KEY_SECRET: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
        run: |
          OSS_ENDPOINT="oss-cn-hangzhou.aliyuncs.com"
          OSS_BUCKET="ai-cs-web"

          ossutil config set \
            --endpoint $OSS_ENDPOINT \
            --access-key-id $OSS_ACCESS_KEY_ID \
            --access-key-secret $OSS_ACCESS_KEY_SECRET

          ossutil rm oss://$OSS_BUCKET/$OSS_PREFIX/ -rf
          ossutil cp dist/ oss://$OSS_BUCKET/ -r
